fasthtml/core.py
nbs/00_core.ipynb
nbs/02_xtend.ipynb
nbs/05_by_example.ipynb

Add intro to core

---

nbs/05_by_example.ipynb

A very minimally-invasive set of improvements. Mostly capitalization and a little grammar.

Very minor improvements to FastHTML by Example

---

nbs/index.ipynb

This PR fills in gaps in the homepage of docs.fastht.ml
* Crafted some nice intro text. I did my best to keep it concise and minimize redundancy.
* Expanded Next Steps with more about the resources, first community link, etc.

Improve the docs index page

---

nbs/tutorials/e2e.ipynb

fixes a little typo in the docs

fix browser typo

---

CONTRIBUTING.md

This tripped me up initially so I decided it might save others some time.

Add nbdev requirement to CONTRIBUTING doc

---

nbs/index.ipynb

* Correct the URL and text
* Grammar

Fix docs index "Hello World!" explanation

---

examples/adv_app.py

just a slightly more sensible default that helps differentiate the content of a todo from its title.

use h2 for todo title in view

---

nbs/explains/explaining_xt_components.ipynb
nbs/tutorials/by_example.ipynb
nbs/tutorials/e2e.ipynb

This PR includes a fix for #134.
Also, improvements for 2 of the tutorials.

Fix typos and rewording for clarity in 'Tutorials' section.

---

nbs/explains/explaining_xt_components.ipynb
nbs/ref/defining_xt_component.ipynb

Created a guide for how to define ft components based on this conversation with @pydanny 
https://discord.com/channels/689892369998676007/1268255595849449535/1268488714795880448

Add defining ft components guide

---

nbs/explains/faq.ipynb

https://x.com/jeremyphoward/status/1819610551703728636

Update faq with JSX question

---

nbs/explains/faq.ipynb

jeremy merged #166 a bit too fast haha, i didnt know his post was about to drop and found the answer in there https://www.answer.ai/posts/2024-08-03-fasthtml.html#why

Update faq.ipynb with a link back to Jeremy's Why post

---

nbs/api/00_core.ipynb

Update 00_core.ipynb (Typo)

---

nbs/ref/defining_xt_component.ipynb

No content changes.  Fixing hyperlinks.  @jph00

Fixing hyperlinks

---

fasthtml/cli.py
nbs/api/09_cli.ipynb

railway deploy doesn't check for project name

---

nbs/ref/defining_xt_component.ipynb

@jph00  Update instructions for tags with invalid symbols to use a dictionary.

Update instructions for tags with invalid symbols

---

CONTRIBUTING.md

- Link to nbdev getting started
- Consistently use `sh` for code fences
- Don't skip markdown heading levels

doc: slight tweaks to CONTRIBUTING.md

---

nbs/tutorials/by_example.ipynb

#286  Updated docs to include recommendation to use WSL on Windows

update server run documentation to recommend WSL for Windows users

---

.github/ISSUE_TEMPLATE/config.yml

Hello,
Added a blank issue template for redirecting the developer/end user to github discussion room and discord server.
As a  result the end user can ask for the help in appropriate dedicated platform and learn from it through fasthtml community.
I have seen in some of the issues that some end users create a issue when then needs some help with their projects. This will give some extra context when they want to create a issue in github.
I have directly added this config.yml configuration file with appropriate data after i created a fork form original repository of main and updated it within my remote github itself. I don't think there will a need to run any nbdev project specific command.
I am not really sure what to add in this pull request template. Since, it was a very simple pull …

Create config.yml for redirecting to github discussion room and discort server

---

nbs/tutorials/by_example.ipynb

---
title: '[PR] '
labels: ''
assignees: ''
---
Describe the big picture of your changes here. If it fixes a bug or resolves a feature request, be sure to link to that issue.
- [ x] Bug fix (non-breaking change which fixes an issue)
**Checklist**

Fixed typo: to_xml() instead of toxml() (Closes #379)

---

examples/first_app.py

---
name: Fixed import error in examples
about: Import error in examples/first_app.py
title: '[PR] Fixed import error in examples/first_app.py'
labels: ''
assignees: ''
---
This PR fixes an import error in `examples/first_app.py`. The error was introduced in [commit 6722c575a72a05cf5a63cf38f4c63d081d66624b](https://github.com/AnswerDotAI/fasthtml/commit/6722c575a72a05cf5a63cf38f4c63d081d66624b) where `Page` changed name to `PageX`.
Changed `Page` -> `PageX` in `examples/first_app.py`.
**Checklist**
`examples/first_app.py` fails to run …

Fixed import error in examples/first_app.py

---

nbs/llms-ctx-full.txt
nbs/llms-ctx.txt
tools/update.sh

The flags were wrong in the script!  Threw me off.  Also the published versions of these are wrong too.  
https://docs.fastht.ml/llms-ctx.txt 
vs
https://docs.fastht.ml/llms-ctx-full.txt
Are the same 😆 .  But no worries.  This fixes that.

fix generation of `llms-ctx*.txt` files

---

nbs/_quarto.yml
nbs/llms.txt
settings.ini

add apilist

---

nbs/llms-ctx-full.txt
nbs/llms-ctx.txt

update ctx with `apilist`

---

nbs/api/05_svg.ipynb

Adds a note regarding explicit SVG element imports 
Documentation update
**Checklist**

Add note on SVG components imports

---

fasthtml/core.pyi
fasthtml/xtend.pyi

I think some interface elements are missing. This was messing up with my other PR so I figured it's better to tackle this before continuing

Add missing interface elements

---

CONTRIBUTING.md

---
name: Add notes re: contributing to FastHTML
about: Contribution docs update
title: '[PR] '
labels: ''
assignees: ''
---
A couple of notes based on my experience contributing to the codebase

Add notes re: contributing to FastHTML

---

nbs/explains/minidataapi.ipynb

---
title: '[PR] Tidy MiniDataSpec spelling and grammar'
assignees: ''
---
This fixes a few minor issues.
**Checklist**

Tidy MiniDataSpec spelling and grammar

---

.github/ISSUE_TEMPLATE/documentation.md

---
title: '[PR] '
labels: ''
assignees: ''
---
Added a new documentation issue template.
**Checklist**

Added documentation template

---

fasthtml/oauth.py
nbs/api/08_oauth.ipynb

It works fine without any scope.  I think its unexpected that it tries to set a user scope for you

[OAuth] remove default scope for GitHub

---

nbs/tutorials/quickstart_for_web_devs.ipynb

---
title: '[PR] Add websockets to quickstart'
assignees: ''
---
Add websockets to the quickstart. In this case, bringing over the [Websockets example](https://docs.fastht.ml/tutorials/by_example.html#websockets) from the By Example tutorial
Also removes the "what's new" admonition and the "What remains to be done" section.
**Checklist**

Add websockets to quickstart

---

nbs/tutorials/jupyter_and_fasthtml.ipynb

---
title: '[PR] Tutorial for using Jupyter and FastHTML together'
assignees: ''
---
#469 Tutorial for using Jupyter and FastHTML together
This is a tutorial designed to demonstrate how to run FastHTML in Jupyter.
**Checklist**

Tutorial: Jupyter and FastHTML

---

nbs/tutorials/by_example.ipynb

---
title: '[PR] Correct link to h2f.answer.ai. Fixes #494'
labels: ' BUG'
assignees: ''
---
#494 
Correct link to h2f.answer..ai
**Checklist**

Correct link to h2f.answer.ai. Fixes #494

---

nbs/tutorials/quickstart_for_web_devs.ipynb

---
title: '[PR] Add file upload to quickstart'
assignees: ''
---
While file upload is described in the handlers document, it isn't in the quickstart.
This PR adds a section for file uploads to the quickstart. It also includes a mild security warning.
**Checklist**
This is for single file uploads, once we have a clear path for multiple file uploads I'll add that to this document.

Add file upload to quickstart

---

README.md
nbs/index.ipynb

Now it worked ;) 
I added one of my blogposts to the README.md.
Thank you!

Added own blogpost to readme.md

---

nbs/tutorials/quickstart_for_web_devs.ipynb

---
title: '[PR] Fix typo in web dev quickstart'
assignees: ''
---
Fix typo in web dev quickstart
- [] Bug fix (non-breaking change which fixes an issue)
**Checklist**

Fix typo in web dev quickstart

---

nbs/api/06_jupyter.ipynb

---
title: '[PR] '
labels: ''
assignees: ''
---
#575 
I tried to improve the docs here. And please change the wording to match the overall style (I'm no native speaker).
**Checklist**
- [ x] I have updated the documentation accordingly.

improved documentation on notebook use

---

nbs/explains/oauth.ipynb

Starting to document the new OAuth class

New intro to oath class in docs

---

nbs/explains/routes.ipynb

---
name: fix imports 
about: Propose fix in document for routing
title: fix imports
labels: fix,update
assignees: ''
---
[link](https://github.com/AnswerDotAI/fasthtml/issues/578)
update import
**Checklist**

fix imports

---

fasthtml/core.py
nbs/api/00_core.ipynb
nbs/ref/handlers.ipynb

---
name: Refactor APIRouter and update documentation
about: Cleans up the `APIRouter` class (e.g., code refactor and getting websockets to route correctl) and adds use information to docs
---
- Refactor `APIRouter` to reuse existing code
- Fix `APIRouter` websocket routes to be `prefix` friendly
- Add brief explanation and demo to documents of how to use `APIRouter`
**Checklist**

Refactor APIRouter and update documentation

---

fasthtml/core.py
nbs/api/00_core.ipynb

---
name: CDN versioning & revisions
about: Use explicit version numbers where possible in the cdn links, along with additional minification where possible 
title: '[PR] '
labels:  "enhancement"
---
Updates to the CDN url's to use fixed version numbers on unpkg links where possible, and addition of a few .min extensions to jsdelivr links. 
**Checklist**

CDN changes

---

nbs/tutorials/by_example.ipynb

---
about: documentation changes
title: '[PR] Misc documentation fixes to the "By Example" tutorial'
labels: ''
assignees: ''
---
- Fix broken links
- Added imports to make it to copy paste snippets

Misc documentation fixes to the "By Example" tutorial

---

fasthtml/components.py
nbs/api/01_components.ipynb

---
about: remove hx_replace_url repeated key from components's hx_attrs_annotations dict
title: '[PR] '
labels: 'cleanup'
assignees: ''
---
[skip]
Remove `hx_replace_url` repeated key from components's `hx_attrs_annotations` dict
**Checklist**
[none]

CLN: remove hx_replace_url repeated key

---

fasthtml/core.py
nbs/api/00_core.ipynb

---
about: upgrade to htmx@2.0.4, fasthtml-js@1.0.12, few htmx_exts to latest version
title: '[PR] '
labels: 'enhancement'
assignees: 'jph00'
---
- Upgrade to htmx@2.0.4 from 2.0.3
- Upgrade to fasthtml-js@1.0.12 from 1.0.4
- Few htmx_exts to latest version
- head-support: Updated from 2.0.1 to 2.0.3.
- preload: Updated from 2.0.1 to 2.1.0.
- ws: Updated from 2.0.1 to 2.0.2.
- Remove spaces after commas
**Checklist**

upgrade to htmx@2.0.4, fasthtml-js@1.0.12, few htmx_exts to latest version

---

fasthtml/core.py
fasthtml/core.pyi
nbs/api/00_core.ipynb

---
title: '[PR] '
labels: ''
assignees: ''
---
@jph00 
#633
When using custom exception handlers, the response status code defaults to 200 instead of preserving the original error code. This occurs unless explicitly returning a HTMLResponse with the correct status code.
- [?] Breaking change (fix or feature that would cause existing functionality to change)
Change fixes the bug from #633 
```python
import requests
from fasthtml.common import *
from fasthtml.jupyter import JupyUvi
def _not_found(req, exc):
print("(404 hit)")
return Titled("404", "Page not found")
def _unauthorized(req, …
```

fixes #633

---

nbs/styles.css

---
title: '[PR] '
labels: ''
assignees: ''
---
See [here](https://github.com/AnswerDotAI/fasthtml/issues/647) for the related issue andmore details.
Tweaked the main docs CSS to give more space around selected menu item, and for menu items that wrap to a newline.
**Checklist**

Tweaked docs menu CSS

---

fasthtml/live_reload.py

> This pr directly correlates to #641 and the format outlined in the associated former PR.
In terms of function, the two code snippets seem to work very similar from local testing. Must ensure credit is given to @dgwyer for this enhancement in the next release notes. 
https://github.com/user-attachments/assets/9a70b289-0553-458d-8e26-4d7a5a1a4eab

Refactored live reload js

---

settings.ini

---
title: '[PR] Add missing monsterui dev dependency'
labels: 'bug'
assignees: 'pydanny'
---
Adds monsterui as a dev dependency, required for tests to pass in CI. Otherwise the concise guide causes failure.
**Checklist**

Add missing monsterui dev dependency

---

nbs/explains/Stripe.ipynb

skip tests for stripe tutorial

---

nbs/ref/concise_guide.ipynb

---
title: '[PR] Document in concise guide how to use MonsterUI with highlighted code'
assignees: 'pydanny'
---
#695
This is a really common desired feature, and it will be easier to launch apps with it turned on. The docs provide enough for an LLM to determine how to turn it off if needed.
**Checklist**

Document in concise guide how to use MonsterUI with highlighted code

---

fasthtml/cli.py
nbs/api/09_cli.ipynb

---
title: '[PR]  Fix Railway CLI command'
labels: ''
assignees: ''
---
https://github.com/AnswerDotAI/fasthtml/issues/780
Just changing the expected name of the railway app.  It appears to have been renamed to just railway and this prevents the cli from working as intended.
- [ X] Bug fix (non-breaking change which fixes an issue)
**Checklist**
- [ X] My code follows the code style of this project.
Any additional information, configuration or data that might be necessary to …

Fix Railway CLI command
