AnswerDotAI/fasthtml

fasthtml/__init__.py
fasthtml/core.py
fasthtml/live_reload.py
fasthtml/starlette.py
nbs/index.ipynb
settings.ini

This PR includes a basic implementation of live reloading.
How does the implementation work?
A subclass of FastHTML (FastHTMLWithLiveReload) does the following: 
- adds a websocket at `/live-reload`
- injects a small javascript snippet `LIVE_RELOAD_SCRIPT` to each webpage
- this snippet allows the browser and server to communicate with each other
- as a result the browser can "detect" code changes on the server and reload
Here are some items to resolve:

Live Reloading

---

fasthtml/fastapp.py

If `picolink` is always set to `True`, then we can't easily use other CSS frameworks.
Addresses #46

Remove picolink in fast_app if default_hdrs is False

---

fasthtml/components.py
nbs/01_components.ipynb

The `cls` argument is now moved to the end of the result of the html2xt function. So this:
```html
<form>
<fieldset>
<input id="title" class="char" name="title" value="Profit"></input>
<label>
<input type="checkbox" data-foo="bar" id="done" class="checkboxer" name="done" checked="1"></input>
Done
</label>
<input type="hidden" id="id" name="id" value="2"></input>
<textarea id="details" name="details">Details</textarea>
<button>Save</button>
</fieldset>
</form>
```
becomes this:
```python
python
Form(
Fieldset(
Input(id='title', name='title', value='Profit', cls='char'),
Label(
Input(type='checkbox', data_foo='bar', id='done', name='done', checked='1', cls='checkboxer'),
'Done'
),
Input(type='hidden', id='id', name='id', value='2'),
Textarea('Details', id='details', name='details'), …
```

In html2xt, move class to end

---

fasthtml/core.py
nbs/00_core.ipynb

Raise error on missing params

---

fasthtml/components.py
nbs/01_components.ipynb
nbs/06_explaining_components.ipynb

Updated html2xt to use unpacked dicts when attr keys are not valid python names.
Also added example of using an unpacked dict to the explaining components nb.
Minimal Example:
```python
hl_md(html2xt_new('<div x-data="{open: false}" x-init="console.log(\'Initialized\')" @click="open = !open">Toggle</div>'))
```
to
```python
Div('Toggle', x_data='{open: false}', x_init="console.log('Initialized')", **{'@click':'open = !open'})
```

Updated html2xt to use unpacked dicts when attr keys are not valid python names

---

nbs/00_core.ipynb
nbs/06_explaining_components.ipynb
nbs/_quarto.yml

Authored by @audreyfeldroy, @pydanny is the typist.
This PR organizes the FastHTML sidebar into three sections mirroring the nbdev sidebar structure:
- Tutorials
- Explanations
- API
This will make it easier for contributors to know where to put these efforts:

Sidebar sections patterned after nbdev

---

fasthtml/fastapp.py

Necessary for websockets to work in `fast_app`. Fixes #80

Fixes the use of websockets in fast_app

---

fasthtml/toaster.py

See #132 
The `.toast` class of FastHTML (`setup_toasts()`) seems to be in conflict with the `.toast` class of bootstrap. 
Since Bootstrap is still very popular, it might be a good idea to namespace the class names to `.fh-toasts` etc. 
(I didn't run the nbdev commands, since the `toaster.py` doesn't seem to be created with nbdev. If that's wrong, I will change the pull request).

changes toast names to avoid conflict with bootstrap

---

nbs/api/00_core.ipynb

The correct type of files on `post` paths is `UploadFile`. I changed it in the PR. 
However, my main issue is that correct file upload requires to set encoding `enctype="multipart/form-data"` and this is not mentioned anywhere. If you don't set it, the request file will passed as a string and contains `[Object file]`. Having the documentation show that string is indeed the correct type (when it's not) just makes it a bit more confusing.
I would lvoe to add this information somewhere so other people can see but I'm unsure where it'd be appropriate. This is a minimal example of what needs to be done for correct file uploads. The relevant bit is:
`enctype="multipart/form-data"` #   <---- without this the file is passed as a string and contains '[Object file]'
```
from fasthtml.common import …
```

fixed uploadFile type hinting

---

fasthtml/live_reload.py

The counter for reload attempts in the JS snippet didn't work, throwing an error in Browser at live reload.

Fixed reloadAttempts variable of JS snippet in live_reload.py

---

fasthtml/fastapp.py

This PR adds the `htmlkw` parameter to the `fast_app` function, allowing it to pass this keyword argument to `FastHTML`.
After this fix, the following code will add `data-theme="light"` to the webpage's `<html>` tag:
```
app, rt = fast_app(htmlkw={"data-theme": "light"})
```

Add htmlkw to fast_app

---

fasthtml/fastapp.py
fasthtml/live_reload.py

Having the values hardcoded to 20 and 250 respectively would cause an unstoppable loop if your reload took more than 250ms
Additionally, created an `app_factory` method for cleaner app type switching

Updated live reload to allow for variable `maxReloadAttempts` and `reloadInterval`

---

fasthtml/js.py

I added a few lines of code to support KaTeX formula rendering. Here is a test case:
```python
from fasthtml.common import *
hdrs = (
MarkdownJS(), HighlightJS(langs=['python', 'javascript', 'html', 'css']),
Link(rel='stylesheet', href='https://cdn.jsdelivr.net/npm/katex/dist/katex.min.css')
)
app, rt = fast_app(hdrs=hdrs)
content = """
Here are some _markdown_ elements.
- This is a list item
- This is another list item
- And this is a third list item
```python
print("Hello, World!")
```
$$
1 \\times 2 = 2
$$
$$1 \\times 2 = 2$$
$1 \\times 2 = 2$
**Fenced code blocks work here.**
"""
@rt('/')
def get(req):
return Titled("Markdown rendering example", Div(content,cls="marked"))
if __name__ == "__main__":
import uvicorn
uvicorn.run(
"__main__:app",
host="0.0.0.0",
port=5001,
reload=True,
) …
```

Add support for LaTeX formula rendering when rendering markdown

---

nbs/tutorials/index.qmd

I noticed a typo in the tutorials index page while reading through the docs and fixed it.

Fixed typo in tutorials index.

---

fasthtml/core.py
nbs/api/00_core.ipynb

Addresses https://github.com/AnswerDotAI/fasthtml/issues/225
- Modified `_from_body` function to handle JSON data
- Implement conditional processing for JSON and form data
- Added test case for JSON POST request
I used the Python virtual env and installed my custom branch as a package to sanity check the changes E2E. I was able to get the same error using the `curl` call and the same code mentioned in the GH Issue. After the changes, the `curl` call worked 🤠 
<details><summary>
</summary>
</details>
<details><summary>
</summary>
</details>
Initially, the test I added failed because the JSON parsing wasn't implemented yet. The screenshot below is a snippet of the error from the test before the changes were added.
```python
-------------------------------------------------------------------- …
```

feat: (#225) Add support for application/json in POST requests

---

examples/adv_app.py

Super small PR: I noticed this function was duplicated while reviewing this example.

Remove duplicated function in example

---

fasthtml/core.py
nbs/api/00_core.ipynb

The docs, specifically [here](https://docs.fastht.ml/tutorials/quickstart_for_web_devs.html#authentication-and-authorization), suggest using
```python
beforeware = Beforeware(
user_auth_before,
skip=[r'/favicon\.ico', r'/static/.*', r'.*\.css', r'.*\.js', '/login', '/']
)
app, rt = fast_app(before=beforeware)
```
to set up user auth, but the '/' route in skip currently matches all routes. It seems the intention was to match the entire route, hence the change to re.fullmatch in this commit.

Use re.fullmatch for Beforeware

---

fasthtml/js.py

This PR improves the `KatexMarkdownJS` function to provide better LaTeX rendering capabilities within Markdown content. Key enhancements include:
1. Support for LaTeX environments (e.g., equation, align, gather, multline)
2. Separate handling for inline and display math
3. Customizable delimiters for inline and display math
4. Configurable list of LaTeX environments to be treated as display math
- Updated `KatexMarkdownJS` function in `fasthtml/js.py`
- Added support for processing LaTeX environments
- Improved regex patterns for more accurate inline and display math detection
- Made math delimiters and environment list customizable
The `katex_tags` parameter has been replaced with separate `inline_delim` and `display_delim` parameters. Users who previously explicitly specified …

Enhance LaTeX rendering in Markdown with support for environments

---

.codespellrc

Running `codespell` with this config results in no false positives and fixes the typos as in #279

chore(ci): add .codespellrc to simplify checking for typos

---

fasthtml/core.py
nbs/api/00_core.ipynb

This addresses a feature request from #200.

Add reload_includes and reload_excludes options to serve

---

examples/adv_app.py

---
title: '[PR] '
labels: ''
assignees: ''
---
The `adv_app.py` example suggests an alternative to importing via `*`: importing the respective objects explicitly. Yet, one object is missing from this enumeration: `FastHTML`. This PR adds this missing object.
**Checklist**

Add missing import in adv example

---

fasthtml/toaster.py
nbs/tutorials/quickstart_for_web_devs.ipynb
tests/test_toaster.py

---
title: '[PR] Set toasts to only work with FT responses'
labels: 'BUG'
assignees: 'pydanny'
---
- #358 
1. Checks that toasts only work with responses that are FT components
2. Documents in the quickstart that toasts only work with FT component responses.
**Checklist**

Set toasts to only work with FT responses

---

nbs/tutorials/by_example.ipynb

Small PR as I'm working my way carefully through this document.  I suspect I will make multiple PRs onto this document. 
Changes made:
1. Use `serve()` instead of Uvicorn
2. Include links in places where there should be links
2. Make some of the language more succint (less is more)
3. Remove the bit about this doc serving as context because there is now `llm-ctx.txt` and friends
4. Update for new `@rt` decorator, and add a tabset panel so people can see the difference
5. Clarify some of the language assuming people are new to web development.
6. Move all `Asides` into Quarto callouts
Im only 25% of the way through just though I would open an early PR.  Don't want to make a big PR if these changes are not aligned with what you want to do!
>[!Important]
> I have generated [a preview link …

Make improvements to `FastHTML By Example`

---

fasthtml/components.py
nbs/api/01_components.ipynb

---
name: Radio Group fill_form fix
about: Make sure only the selected radio button in a radio group is checked during form_fill
title: '[PR] '
labels: ''
assignees: ''
---
https://github.com/AnswerDotAI/fasthtml/issues/423
This handles radio type inputs separately to check if the value key of the radio input is equal to the `val` of the `obj` that is filling in the radio group
**Checklist**
See the issue: https://github.com/AnswerDotAI/fasthtml/issues/423
this is the working mre where refreshing the page keeps the radio selection on True

[Fix] Make sure only the selected radio button in a radio group is checked during form_fill

---

fasthtml/xtend.py
nbs/api/02_xtend.ipynb

---
title: '[PR] '
labels: ''
assignees: ''
---
Updated the `Nbsp()` component to render the space HTML entity. At the moment it renders the text `nbsp;`. I think it was just a case of a missing ampersand character.
**Checklist**

Fixed Nbsp component

---

fasthtml/jupyter.py
nbs/api/06_jupyter.ipynb

---
title: '[PR] '
labels: ''
assignees: ''
---
Allow specifying iframe height explicitly when using HTMX in jupyter. As per discussion on discord, some jupyter notebook clients do not display the whole content of the page. Supporting explicit height setting helps address this. Tested with VScode Jupyter 
**Checklist**

Support explicit iframe height in Jupyter HTMX

---

fasthtml/core.py
nbs/api/00_core.ipynb

---
title: '[PR] '
labels: ''
assignees: ''
---
https://github.com/AnswerDotAI/fasthtml/issues/451
Updates the initialization of `FastHTML` to call parent class Starlette with keyword args.
**Checklist**

Make compatible w/ ddtrace

---

nbs/explains/oauth.ipynb

---
title: '[PR] '
labels: ''
assignees: ''
---
The recent PR merge for the OAuth docs showed a couple of formatting issues that needed to be resolved such as vertical spacing around the GitHub oauth image and the note box (see screenshot).
I changed the margin values for the image based on editing the live FastHTML docs HTML via the inspector until it looked.
Here is what it looked like before.

Corrected some formatting issues

---

nbs/tutorials/e2e.ipynb

Missing leave room button in step by step setup of the room page.

add missing Leave Room button in e2e tutorial

---

fasthtml/live_reload.py
nbs/ref/live_reload.ipynb
nbs/tutorials/by_example.ipynb

The Hello World example at the beginning of the [tutorial](https://docs.fastht.ml/tutorials/by_example.html) returns a raw HTML string, so it's not compatible with live reload. For the hypothetical eager reader who follows the callout tip and enables live reloading before continuing with the tutorial, this is tricky to debug. 
Changes:
- Add a note to the Live Reload "Gotchas" section about the need to use ft components 
- Is this the correct term? The docs seem to use "ft components", "FT components", and "FT objects" interchangeably.
- Move the live reload callout tip further down in the tutorial after components have been introduced
- I didn't want to make any major changes to the tutorial flow, but personally I think it would be a nicer learning experience to just dive straight into …

Update live reload documentation

---

fasthtml/jupyter.py
nbs/api/06_jupyter.ipynb

---
title: '[PR] '
labels: ''
assignees: ''
---
[Please link to the issue that this pull request addresses. If there isn't one, please create an issue first.
](https://github.com/AnswerDotAI/fasthtml/issues/503)
Currently you need to pass a string to `HTMX` to render in notebook.  Ideally, you can just pass the function that was decorated.  This allows you to do that by stringifying what is passed in.  In the screenshot, note that I am passing the function that was decorated and NOT a string.
**Checklist** …

Allows for passing route functions

---

nbs/tutorials/jupyter_and_fasthtml.ipynb

---
title: '[PR] Jupy tuturial add two segments'
assignees: ''
---
#487 [DOCS] More features for the Jupyter+FastHTML demo
An abridged version of an earlier PR, adds two segments to docs:
- Full screen view
- Graceful shutdowns
**Checklist**
This PR is intentionally small and designed to be easy for avoiding merge conflicts.

Jupy tuturial add two segments

---

fasthtml/toaster.py
nbs/tutorials/quickstart_for_web_devs.ipynb
tests/test_toaster.py

---
about: Fix for issues 486
title: '[PR] Allow toasts to work with FtResponse'
labels: 'bug', 'hacktoberfest'
assignees: ''
---
[[BUG] FtResponse breaks toasts](https://github.com/AnswerDotAI/fasthtml/issues/486)
Add FtResponse to list of supported response types
**Checklist**

Allow toasts to work with FtResponse

---

nbs/tutorials/quickstart_for_web_devs.ipynb

---
title: '[PR] Document multiple file support'
assignees: ''
---
Add documentation for multiple file uploads. Rather than a combined example, or a single file upload, it separates the single- and multi-file uploads into two examples. This approach provides several benefits:
1. Provide easy-to-copy examples that just work
2. It is easier to maintain and test these docs compared to other approaches
Note: This is a rewrite of #534 to get around a problem with rebasing and notebooks.
**Checklist**

Document multiple file uploads

---

fasthtml/fastapp.py

---
name: `nb_hdrs` in fast_app
about: `nb_hdrs` arg from `FastHTML` missing from `fast_app
title: '[PR] '
labels: ''
assignees: ''
---
The `FastHTML` class has `nb_hdrs` argument which allows you to opt out of headers being injecting into notebook dom.  This PR adds that to `fast_app` as well so the option exists there as well.
**Checklist**

Add nb_hdrs to fast_app

---

nbs/tutorials/quickstart_for_web_devs.ipynb

---
title: '[PR] Convert quickstart Python modules to markdown'
labels: 'bug,documentation'
assignees: ''
---
#553 Quickstart sidebars are broken
Change the Python segments that call `serve()` to Markdown. The `serve()` is interfering with Quarto's ability to render cells. Something likely to do with uvicorn trying to serve those segments out.
**Checklist**

Convert quickstart Python modules to markdown

---

nbs/explains/minidataapi.ipynb
nbs/tutorials/quickstart_for_web_devs.ipynb

---
title: '[PR] Case and spelling corrections'
assignees: ''
---
#474
- Capitalising and grammar corrections
- State that setting `.xtra` is a one-way operation
**Checklist**

Minidata API Spec cleanup

---

fasthtml/core.py
nbs/api/00_core.ipynb
nbs/explains/websockets.ipynb

---
title: '[PR] '
labels: ''
assignees: ''
---
In order to access session data in ws handler right now, you need to drill into `ws.session`. While standard route handlers provide `session/sess` shortcut, `ws` handlers do not.
This PR adds support for `session/sess` param inside `ws` handlers. Includes a quick test + doc 
**Checklist**

Incl session param in ws

---

fasthtml/components.py
nbs/api/01_components.ipynb

---
title: '[PR] '
labels: ''
assignees: ''
---
#565 
Describe the big picture of your changes here. If it fixes a bug or resolves a feature request, be sure to link to that issue.
Modified `_fill_item()` to resolve the issue.
Included tests to show proper operation.
**Checklist**

fixing issue #565, improper initialization of multiple select and checkbox arrays

---

fasthtml/live_reload.py
fasthtml/toaster.py

---
name: toast js + livereload js cleanup
about: use `%` notation instead of `.format` in toast js & livereload js
title: '[PR] '
labels: 'cleanup'
assignees: ''
---
This is a followup to [PR 587](https://github.com/AnswerDotAI/fasthtml/pull/587#issuecomment-2492261266)
Use % notation instead of .format in toast js + livereload js
**Checklist**

use % notation instead of .format in toast js & livereload js

---

fasthtml/js.py
nbs/api/03_js.ipynb

---
name: Highlightjs Fixes
about: Tiny changes to the js.py file
title: '[PR] '
labels: ''cleanup"
assignees: ''
---
Changed the default css selector in the Highlightjs function to work better with the HTMX onload functionality, so it doesn't try and re-highlight previous elements. Stops the console messages about already highlighted elements. Also just a small typo i saw.
**Checklist**

Highlightjs Fixes

---

fasthtml/core.py
nbs/api/00_core.ipynb

---
name: Adds "body_wrap" bits to APIRouter
about: Added the ability to define a `body_wrap` function for `APIRouter`
title: Adds "body_wrap" bits to APIRouter
---
N/A
This PR brings `APIRouter` inline with `FastHTML` w/r/t having the ability to define a top-level `body_wrap` function to be across all related routes.
**Checklist**
N/A

Adds "body_wrap" bits to APIRouter

---

nbs/tutorials/by_example.ipynb

---
about: since port will default to 5001 or the PORT environment variable. This PR makes the doc change to 5001 from 8000.
title: '[PR] doc: default port 5001'
assignees: 'jph00'
---
Since port will default to 5001 or the PORT environment variable. I think, it's helpful for to use 5001, instead of 8000. (which may cause some confusion with new adopters)
https://docs.fastht.ml/tutorials/by_example.html
**Checklist**

doc: default port 5001

---

fasthtml/core.py
nbs/api/00_core.ipynb

#620 
I'm deploying a FastHTML app to AWS Lambda, and extra imports cause longer cold starts. I did a naive test (3 samples of each) and it seems like this uvicorn import takes 10-25ms to load.
I list it as a bugfix below, but I don't think it's really a bug.
**Checklist**

Suggestion: don't import uvicorn to allow for alternative asgi servers

---

fasthtml/core.py
nbs/api/00_core.ipynb

---
about: Allow qp (and therefore `.to` method) to handle params with `?a=1` or `/a` situations
title: '[qp improvement] '
labels: 'enhancement'
assignees: 'isaac-flath'
---
[Please link to the issue that this pull request addresses. If there isn't one, please create an issue first.
](https://github.com/AnswerDotAI/fasthtml/issues/637)
Allow qp (and therefore `.to` method) to handle params with `?a=1` or `/a` situations
**Checklist**
Any additional information, configuration or data that might be necessary to reproduce …

Handling for query or url params in qp/to

---

fasthtml/core.pyi
nbs/apilist.txt
nbs/llms-ctx-full.txt
nbs/llms-ctx.txt
nbs/llms.txt

This PR  expands the optional section in fasthtml's llms.txt to include all tutorials and explanations.
Changes:
- Added all the tutorials and explanations to the optional section in llms.txt
- Updated corresponding ctx and ctx-full versions to match
- Fixed description of qp() function in the `core.pyi` using the `tools/update.sh` script.
These changes help ensure developers utilizing our llms.txt are able to get access to all our documentation.

docs: update documentation links and add tutorials to optional section

---

nbs/ref/handlers.ipynb

Fix typo in docs. Reference `to()` instead of `rt()`.

handlers.ipynb : fix typo

---

fasthtml/toaster.py

---
about: Fix for duplicate toast containers
title: '[PR] '
labels: ''
assignees: ''
---
Mentioned in the FastHTML discord by user `78wesley` and validated locally.
Toast containers were being spawned in overlapping contexts and thus rendering incorrectly when using multiple `add_toast` methods. 
I've been through the gist provided by 78wesley in the discord, and it did indeed fix the issue. I've done a cleanup/ revamp of the `toaster.py` file to fix the issues, and also removed the javascript in favour of htmx.
**Checklist**
**Demo** …

Toast container duplication fix

---

nbs/explains/explaining_xt_components.ipynb

---
title: '[PR] '
labels: ''
assignees: ''
---
[Issue 676](https://github.com/AnswerDotAI/fasthtml/issues/676)
Fix Markup for link - add missing html
**Checklist**
This is a simple fix just fixed a link in the docs.

Fix broken link on ..explaines/FtComponents Page

---

fasthtml/core.py
nbs/api/00_core.ipynb
tests/test_toaster.py

---
title: '[PR] '
labels: ''
assignees: ''
---
https://github.com/AnswerDotAI/fasthtml/issues/635
I saw the issue and that when typed hinted, session was being handled as body. I was not sure whether to create or new function or just handle before as body is also a `dict`. Looks like this may also be true for other args like `auth` which I can add here (but wasn't sure it was ever a function arg).
**Checklist**
Any additional information, configuration or data that might be …

handle for when there is a type hint on session

---

fasthtml/core.py
nbs/api/00_core.ipynb
nbs/explains/background_tasks.ipynb

---
title: '[PR] Correct background tasks when used by FtResponse'
labels: 'bug'
assignees: ''
---
#336 - Background Tasks
This PR makes it possible for the FtResponse class to handle Background Tasks
**Checklist**

Fix+docs for background tasks when used by FtResponse

---

fasthtml/core.py
nbs/api/00_core.ipynb

If the user doesn't include all request params in their request a `KeyError` will be raised when running `_find_p`.
---
title: '[PR] '
labels: ''
assignees: ''
---
#693 
This pr updates `_formitem` so that is does a safe dict lookup and no longer throws a `KeyError`.
**Checklist**
N/A

update `_formitem` so that it doesn't raise `KeyError`

---

fasthtml/toaster.py
nbs/tutorials/quickstart_for_web_devs.ipynb
tests/test_toaster.py

---
title: '[PR] '
labels: ''
assignees: ''
---
#703 
I think the underlying issue is that we're attempting to do an oob swap before the target element (toast container) has been inserted into the DOM.
This pr updates `toaster.py` so that toasts are inserted at the top of the page. 
**Checklist**
Here's a demo of bug and solution
https://github.com/user-attachments/assets/05b1c5da-86d7-4f95-b560-3b2ca6f1198e

inserts toasts at top of the page

---

fasthtml/fastapp.py

---
title: '[PR] allow default title to be set from fast_app()'
labels: ''
assignees: ''
---
https://github.com/AnswerDotAI/fasthtml/issues/485
(https://github.com/AnswerDotAI/fasthtml/pull/604)
This PR would add a `title=` kwarg to the `fast_app()` constructor, and have the effect of allowing a default page title to be set. It needn't do very much, because the underlying functionality was added to `FastHTML()` in #604 ; this PR just connects them.
**Checklist**
Go over all the …

add title= kwarg to fast_app() constructor

---

fasthtml/components.py
nbs/api/01_components.ipynb

#737 
Dictionaries are allowed as a child of fasttags, which turns them into attributes. This change makes it so that any Mapping can be used for this, rather than just `dict`s. The purpose is to allow helpers to generate attributes that don't have to subclass the builtin `dict`.
**Checklist**

[PR] Allow any Mapping children to specify attributes. fix #737

---

nbs/ref/defining_xt_component.ipynb

---
title: '[PR] Improve custom components docs'
assignees: ''
---
Issue #713 and this supersedes PR #715.
The current custom docs leads with `NotStr`, mixes details about automatic and manual creation of tags, and could introduct handling special cases better.
- Moves `NotStr` to the end introduced as a last-ditch patch 
- Moves details of how automatic creation works out of manual creation and to where it belongs: automatic creation
- Puts special cases like special characters into their own dedicated "Special Cases" section. 
**Checklist**
Go over all the …

Improvements to the custom components docs

---

fasthtml/toaster.py
nbs/api/00_core.ipynb

#762 
This pr updates `render_toasts` so that toasts are always inserted into the toast container for regular page loads and htmx requests. The pr also includes a regression test.
**Checklist**
N/A

fix broken toasts
